plugins {
    id 'com.android.application'
}

android {
    namespace 'de.atmspro.app'
    compileSdk 35

    defaultConfig {
        applicationId 'de.atmspro.app'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.4.0-p31f12'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
